name             'kirby'
maintainer       'The Authors'
maintainer_email 'you@example.com'
license          'all_rights'
description      'Installs/Configures kirby'
long_description 'Installs/Configures kirby'
version          '0.1.0'

depends 'nginx', '~> 2.7.6'
depends 'composer', '~> 2.2.1'
