name             'kirby_cli'
maintainer       'The Authors'
maintainer_email 'you@example.com'
license          'all_rights'
description      'Installs the Kirby CLI'
long_description 'Installs the Kirby CLI'
version          '0.1.0'

depends 'nginx', '~> 2.7.6'
depends 'composer', '~> 2.2.1'